//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTMLCompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTMLCompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;PTM&lt;/title&gt;
        ///    &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///    &lt;script src=&apos;ptm.js&apos;&gt;&lt;/script&gt;
        ///    &lt;script&gt;
        ///        document.addEventListener(&apos;DOMContentLoaded&apos;, main, false);
        ///    &lt;/script&gt;
        ///    &lt;style&gt;
        ///        canvas, #overlay {
        ///            padding: 0;
        ///            margin: auto;
        ///            display: block;
        ///            position: absolute;
        ///            top: 0;
        ///            bottom: 0;
        ///            left: 0;
        ///            right: 0;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ptm_html {
            get {
                return ResourceManager.GetString("ptm_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //=============================================================================
        /////
        /////      PTM - Programmable Tile Machine
        /////      2021 developed by Fernando Aires Castello
        /////      https://github.com/FernandoAiresCastello
        /////
        /////=============================================================================
        ///
        ///class Util {
        ///
        ///    static ByteToBinaryString(value) {
        ///        return value.toString(2).padStart(8, &apos;0&apos;);
        ///    }
        ///}
        ///
        /////============================================================================ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ptm_js {
            get {
                return ResourceManager.GetString("ptm_js", resourceCulture);
            }
        }
    }
}
