//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///INT
        ///[
        ///	int {0} = {1};
        ///]
        ///
        ///STR
        ///[
        ///	std::string {0} = {1};
        ///]
        ///
        ///MSGBOX
        ///[
        ///	Sys-&gt;ShowMsgBox({0});
        ///]
        ///
        ///HALT
        ///[
        ///	Sys-&gt;Halt();
        ///]
        ///
        ///EXIT
        ///[
        ///	Sys-&gt;Exit();
        ///]
        ///
        ///SCREEN
        ///[
        ///	Scr-&gt;OpenWindow({0}, {1}, {2}, {3});
        ///]
        ///
        ///BGCOLOR
        ///[
        ///	Scr-&gt;SetBackColorIx({0});
        ///]
        ///
        ///CLS
        ///[
        ///	Scr-&gt;Clear();
        ///]
        ///
        ///LOOP
        ///[
        ///	while (true) { 
        ///		Sys-&gt;ProcessGlobalEvents();
        ///]
        ///
        ///FOR
        ///[
        ///	for ({0} = {1}; {0} &lt; {2}; {0} += {3}) {{
        ///]
        ///
        ///NEXT
        ///[
        ///	}
        ///]
        ///
        ///CALL
        ///[
        ///	{0}();
        ///]
        ///
        ///RET
        ///[
        ///	}
        ///]
        ///.
        /// </summary>
        internal static string cmd {
            get {
                return ResourceManager.GetString("cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //=============================================================================
        /////	INCLUDES
        /////=============================================================================
        ///#include &lt;windows.h&gt;
        ///#include &lt;SDL.h&gt;
        ///#include &lt;map&gt;
        ///#include &lt;string&gt;
        ///#include &lt;vector&gt;
        ///
        /////=============================================================================
        /////	FORWARD DECLARATIONS
        /////=============================================================================
        ///class Context;
        ///class System;
        ///class Screen;
        ///
        /////==== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ptm_cpp {
            get {
                return ResourceManager.GetString("ptm_cpp", resourceCulture);
            }
        }
    }
}
