//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;SDL2/SDL.h&gt;
        ///#include &lt;windows.h&gt;
        ///#include &lt;cstdio&gt;
        ///#include &lt;cstdarg&gt;
        ///#include &lt;cctype&gt;
        ///#include &lt;string&gt;
        ///#include &lt;vector&gt;
        ///#include &lt;iostream&gt;
        ///#include &lt;sstream&gt;
        ///#include &lt;fstream&gt;
        ///#include &lt;algorithm&gt;
        ///#include &lt;bitset&gt;
        ///
        ///#define WINDOW_TITLE &quot;Hello World!&quot;
        ///#define WINDOW_WIDTH 640
        ///#define WINDOW_HEIGHT 480
        ///#define WINDOW_FULLSCREEN 0
        ///#define SCREEN_WIDTH 160
        ///#define SCREEN_HEIGHT 96
        ///
        /////=============================================================================
        /////      UTIL        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ptm {
            get {
                return ResourceManager.GetString("ptm", resourceCulture);
            }
        }
    }
}
